language: python 
python:
- "2.7" 
- "3.6"
branches:
    only:
    - master
services:
- postgresql
env: 
- DJANGO_VERSION=2.0 DB=postgres
- DJANGO_VERSION=1.11 DB=postgres
global:
- PGPORT=5432
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
- pip install -q Django==$DJANGO_VERSION
- python setup.py -q install
before_script: 
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py migrate
script: 
- python manage.py test
addons:
  postgresql: "9.6"
